export const works = [
  {
    title: 'Software Engineer',
    type:'Full-Time',
    company:'Xelpmoc Design And Tech Ltd.',
    location:'Bangalore',
    company_url:'https://www.xelpmoc.in/',
    description: "Developed and maintained code for in-house and client websites primarily using Next.js, React.js, Redux.js toolkit, JavaScript, and Material UI, Tailwind CSS. Also, manually tested sites in various browsers and mobile devices to ensure cross-browser compatibility and responsiveness.",
    // image: '/images/covid.jpg',
    tags: ['Next.js', 'React.js', 'Redux.js Toolkit',],
    othertags:[ 'JavaScript', 'HTML/CSS'],
    duration:'Dec 2022 - Present',
    // source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    // visit: 'https://project.vipuljha.com/covid/',
    id: 0,
  },
  {
    title: 'Full Stack Developer',
    type:'Internship',
    company:'Xelpmoc Design And Tech Ltd.',
    location:'Bangalore',
    company_url:'https://www.xelpmoc.in/',
    description: "Worked on an US-based industry-level project built in React.js and also used Redux.js toolkit.",
    // image: '/images/covid.jpg',
    tags: ['React.js', 'Redux.js Toolkit',],
    othertags:[ 'JavaScript', 'HTML/CSS'],
    duration:'Aug 2022 - Dec 2022 ',
    // source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    // visit: 'https://project.vipuljha.com/covid/',
    id: 1,
  },
  {
    title: 'Full Stack Developer',
    type:'Internship',
    company:'Aurbitus',
    location:'Gwalior',
    company_url:'https://aurbitus.com/',
    description: "Made a MERN Stack Project for a MLM-based client Service Point India (SPI), with an E-Commerce layout, also lead the team of 2 members & have hands on experience on React.js & Node.js.",
    // image: '/images/covid.jpg',
    tags: ['React.js', 'Node.js', 'MongoDB'],
    othertags:[ 'JavaScript', 'HTML/CSS'],
    duration:'Jan 2022 - Mar 2022',
    // source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    // visit: 'https://project.vipuljha.com/covid/',
    id: 2,
  },
  {
    title: 'Full Stack Developer',
    type:'Internship',
    company:'Numeric Infosystem Pvt. Ltd.',
    location:'Gwalior',
    company_url:'https://www.numericinfosystems.com/',
    description: "Made Student Marksheet Management System & Product Management System using Node.js.",
    // image: '/images/covid.jpg',
    tags: ['Node.js', 'MySQL'],
    othertags:[ 'JavaScript', 'HTML/CSS'],
    duration:'July 2021 - Dec 2021',
    // source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    // visit: 'https://project.vipuljha.com/covid/',
    id: 3,
  },
  
];

export const TimeLineData = [
  { year: 'B.Tech (IT)', text: '2019-2023 | ITM, Gwalior', },
  { year: 'XII', text: '2017-2018 | Sarvodaya Sr. Secondary, Kota', },
  { year: 'X', text: '2015-2016 | SSMV, Shahjahanpur', },
  // { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
  // { year: 2020, text: 'Got a scholarship from the Delhi government.', },
  // { year: 2021, text: 'Still trying to figure out this weird year.', },
];

export const ProjectsData = [
  {
    name:'TextZone',
    details:"The main purpose of the project is to provide users with an messaging tool to contact others when needed and can be easily done. The application is designed as a web application. It is different from other chat web applications because the backend logic is kept at minimal and doesn't involve web-sockets for end to end user chats. Also, FireBase Auth Service is used for phone number verification.",
    tech:['React.js' , 'Node.js' , 'MongoDB'],
    othertech:['JavaScript' , 'HTML/CSS'],
    github:'https://github.com/abhayChandra01/TextZone',
  },
  {
    name:'Learning Management System (LMS)',
    details:"LMS is a software application which handles all aspects of a learning process, including the administration, documentation, tracking, reporting, automation, and delivery of educational courses. There are Admin Panels, Faculty Panels & Student Dashboards to provide better clarity and accesses to different options. It's main feature is to provide a platform to conduct online examinations for students via faculties.",
    tech:['React.js' , 'Node.js', 'Redux.js' , 'MySQL'],
    othertech:['JavaScript' , 'HTML/CSS'],
    github:'https://github.com/abhayChandra01/LearningManagementSystem',
  },
  {
    name:'Product Management System',
    details:"This project is a type of inventory management system that allows user to manage and maintain his/her inventory with ease. The inventory management system has been developed to allow users to add an inventory, delete an inventory, enter inventory quantity and other details, update inventory status and more.",
    tech:['Node.js' , 'MySQL'],
    othertech:['JavaScript' , 'HTML/CSS'],
    github:'https://github.com/abhayChandra01/ProductManagementSystem',
  },
  {
    name:'Marksheet Management System',
    details:"This is a software application that can automatically generate marks of the students in the form of grades. Students can view and download their specific marksheet through the platform.",
    tech:['Node.js' , 'MySQL'],
    othertech:['JavaScript' , 'HTML/CSS'],
    github:'https://github.com/abhayChandra01/MarksheetManagementSystem',
  },
]